# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(863, 774)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(10, 480, 840, 280))
        self.widget2.setObjectName("widget2")
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(10, 200, 840, 280))
        self.widget1.setObjectName("widget1")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 211, 191))
        self.groupBox.setObjectName("groupBox")
        self.textBoxFl = QtWidgets.QLineEdit(self.groupBox)
        self.textBoxFl.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.textBoxFl.setObjectName("textBoxFl")
        self.textBoxFh = QtWidgets.QLineEdit(self.groupBox)
        self.textBoxFh.setEnabled(True)
        self.textBoxFh.setGeometry(QtCore.QRect(80, 90, 113, 20))
        self.textBoxFh.setObjectName("textBoxFh")
        self.buttonSet = QtWidgets.QPushButton(self.groupBox)
        self.buttonSet.setGeometry(QtCore.QRect(80, 150, 111, 23))
        self.buttonSet.setObjectName("buttonSet")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.comboBoxFilterType = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxFilterType.setGeometry(QtCore.QRect(80, 30, 111, 22))
        self.comboBoxFilterType.setObjectName("comboBoxFilterType")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_3.setObjectName("label_3")
        self.spinBoxOrder = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxOrder.setGeometry(QtCore.QRect(80, 120, 111, 22))
        self.spinBoxOrder.setMaximum(50)
        self.spinBoxOrder.setObjectName("spinBoxOrder")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 0, 611, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label1 = QtWidgets.QLabel(self.groupBox_2)
        self.label1.setGeometry(QtCore.QRect(320, 40, 47, 13))
        self.label1.setObjectName("label1")
        self.horizontalSlider3 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider3.setGeometry(QtCore.QRect(50, 100, 251, 22))
        self.horizontalSlider3.setMaximum(5000)
        self.horizontalSlider3.setPageStep(100)
        self.horizontalSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider3.setObjectName("horizontalSlider3")
        self.label2 = QtWidgets.QLabel(self.groupBox_2)
        self.label2.setGeometry(QtCore.QRect(320, 70, 47, 13))
        self.label2.setObjectName("label2")
        self.horizontalSlider1 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider1.setGeometry(QtCore.QRect(50, 40, 251, 22))
        self.horizontalSlider1.setMaximum(5000)
        self.horizontalSlider1.setPageStep(100)
        self.horizontalSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider1.setObjectName("horizontalSlider1")
        self.label3 = QtWidgets.QLabel(self.groupBox_2)
        self.label3.setGeometry(QtCore.QRect(320, 100, 47, 13))
        self.label3.setObjectName("label3")
        self.horizontalSlider2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider2.setGeometry(QtCore.QRect(50, 70, 251, 22))
        self.horizontalSlider2.setMaximum(5000)
        self.horizontalSlider2.setPageStep(100)
        self.horizontalSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider2.setObjectName("horizontalSlider2")
        self.label1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_2.setGeometry(QtCore.QRect(20, 40, 31, 16))
        self.label1_2.setObjectName("label1_2")
        self.label1_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_3.setGeometry(QtCore.QRect(20, 70, 31, 16))
        self.label1_3.setObjectName("label1_3")
        self.label1_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_4.setGeometry(QtCore.QRect(20, 100, 31, 16))
        self.label1_4.setObjectName("label1_4")
        self.label1_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_5.setGeometry(QtCore.QRect(10, 140, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label1_5.setFont(font)
        self.label1_5.setObjectName("label1_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "FIR Filter Analysis"))
        self.groupBox.setTitle(_translate("Dialog", "Filter Type"))
        self.buttonSet.setText(_translate("Dialog", "Set"))
        self.label.setText(_translate("Dialog", "Cut Off Low :"))
        self.label_2.setText(_translate("Dialog", "Cut Off High :"))
        self.label_3.setText(_translate("Dialog", "Filter Type :"))
        self.label_4.setText(_translate("Dialog", "Filter Order :"))
        self.groupBox_2.setTitle(_translate("Dialog", "Frequencys"))
        self.label1.setText(_translate("Dialog", "0 Hz"))
        self.label2.setText(_translate("Dialog", "0 Hz"))
        self.label3.setText(_translate("Dialog", "0 Hz"))
        self.label1_2.setText(_translate("Dialog", "F1 :"))
        self.label1_3.setText(_translate("Dialog", "F2 :"))
        self.label1_4.setText(_translate("Dialog", "F3 :"))
        self.label1_5.setText(_translate("Dialog", "Input Signal = sin(2*pi*F1*x) + sin(2*pi*F2*x) + sin(2*pi*F3*x) "))

